name = "DocumenterDiagrams"
uuid = "a106ebf2-4182-4cba-90d4-44cd3cc36e85"
authors = ["Pedro Maciel Xavier <pedromxavier@poli.ufrj.br>"]
version = "1.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Kroki = "b3565e16-c1f2-4fe9-b4ab-221c88942068"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Documenter = "1"
Kroki = "0.2"
MarkdownAST = "~0.1"
TranscodingStreams = "=0.9.11"
julia = "1.6"
